server:
  port: 8080
  compression: #embedded tomcat 기동 시에 사용되는 설정. tomcat server 에서 실행할 경우는 server.xml 에 설정.
    min-response-size: 1
    enabled: true

spring:
  application:
    name: flight-cws-api
  config:
    activate:
      on-profile: local
#  output:
#    ansi:
#      enabled: true

  # 404 not found settings
  #mvc:
  #  throw-exception-if-no-handler-found: true
