server:
  port: 8980
spring:
  application:
    name: router-server
  kafka:
    bootstrap-servers: 144.24.91.88:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: router-server-group-default
    template:
      default-topic: cws-item-topic-default

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus
          - env
          - httptrace
logging:
  level:
    io.cws: debug
---
server:
  port: 8080
  compression: #embedded tomcat 기동 시에 사용되는 설정. tomcat server 에서 실행할 경우는 server.xml 에 설정.
    min-response-size: 1
    enabled: true

spring:
  config:
    activate:
      on-profile: local
#  output:
#    ansi:
#      enabled: true

  # 404 not found settings
  #mvc:
  #  throw-exception-if-no-handler-found: true

---
spring:
  application:
    name: router-server
  config:
    activate:
      on-profile: prd
  kafka:
    consumer:
      group-id: router-server-group-prd
    template:
      default-topic: cws-item-topic-prd