server:
  port: 8880

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true

  kafka:
    bootstrap-servers: 144.24.91.88:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springframework.data: warn
    h2: debug
    io.cws: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus
          - env
          - httptrace

springdoc:
  packages-to-scan:
    - io.cws
---
spring:
  config:
    activate:
      on-profile: default
  kafka:
    template:
      default-topic: cws-item-topic-default
  datasource:
    url: jdbc:h2:mem:db1;MODE=MySql;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: prd
  kafka:
    template:
      default-topic: cws-item-topic-prd
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.mariadb.jdbc.Driver