spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    org.springframework.data: warn
    h2: debug
    io.cws: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus
          - env

springdoc:
  packages-to-scan:
    - io.cws
---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:db1;MODE=MySql;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: prd
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.mariadb.jdbc.Driver